# Overall filter parameters
min_particles: 500
max_particles: 5000
kld_err: 0.05
kld_z: 0.99
update_min_d: 0.2
update_min_a: 0.05
resample_interval: 1
transform_tolerance: 0.1
recovery_alpha_slow: 0.01
recovery_alpha_fast: 0.1
gui_publish_rate: 5.0
use_map_topic: false

# Laser model parameters
laser_min_range: -1.0
laser_max_range: -1.0
laser_max_beams: 30
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

# Odometery model parameters
odom_model_type: diff
odom_alpha1: 2.5
odom_alpha2: 2.5
odom_alpha3: 2.5
odom_alpha4: 2.5