TrajectoryPlannerROS:
  # Robot configuration parameters
  acc_lim_x: 0.1 
  acc_lim_y: 0.1
  acc_lim_theta: 0.3
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_theta: 0.5
  min_vel_theta: 0.12
  min_in_place_vel_theta: 0.12
  escape_vel: -0.1
  holonomic_robot: false

  # Goal tolerance parameters
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance:  0.15
  latch_xy_goal_tolerance: false

  # Forward simulation parameters
  sim_time: 2.0

  # Trajectory scoring parameters
  meter_scoring: true
  pdist_scale: 0.8
  occdist_scale: 0.05
  heading_lookahead: 0.325
  dwa: false
  publish_cost_grid_pc: false
  # Frame for planner map
  global_frame_id: map

  # Oscillation prevention parameters
  oscillation_reset_dist: 0.05

  # Gloabal plan parameters
  prune_plan: true
