obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.276, 0.2835], [0.276, -0.2835], [-0.276, -0.2835], [-0.276, 0.2835]]
robot_radius: 0.5
inflation_radius: 0.8

obstacles:
  observation_sources: laser_scan_sensor kinect_scan
  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true}
  kinect_scan: {sensor_frame: camera_link, data_type: LaserScan, topic: scan2, marking: true, clearing: true}
