DWAPlannerROS:
  acc_lim_th: 0.6
  acc_lim_x: 0.2
  acc_lim_y: 0.2

  max_vel_x: 0.4
  min_vel_x: 0.0

  max_vel_y: 0.2
  min_vel_y: -0.2

  max_trans_vel: 0.4
  min_trans_vel: 0.2

  max_rot_vel: 0.6
  min_rot_vel: 0.2

  sim_time: 1.7
  sim_granularity: 0.025

  goal_distance_bias: 20.0
  path_distance_bias: 30.0
  occdist_scale: 0.01

  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.05

  forward_point_distance: 0.325

  scaling_speed: 0.25
  max_scaling_factor: 0.2

  vx_samples: 3
  vy_samples: 10
  vtheta_samples: 20

  sim_period: 0.1

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.17

  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01
