global_costmap:
  update_frequency: 4.0
  static_map: true
  map_type: costmap
  plugins:
     - {name: static_map, type: "costmap_2d::StaticLayer" }
     - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
     - {name: inflater, type: "costmap_2d::InflationLayer"}
