global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 4.0
  static_map: true
  map_type: costmap
  plugins:
     - {name: static_map, type: "costmap_2d::StaticLayer" }
     - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
     - {name: downstairs, type: "nav_layer_from_points::NavLayerPoints"}
     - {name: inflater, type: "costmap_2d::InflationLayer"}
