local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 2.0
  static_map: false
  map_type: costmap
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.05
  plugins:
    - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
    - {name: inflater, type: "costmap_2d::InflationLayer"}
    - {name: downstairs, type: "nav_layer_from_points::NavLayerPoints"}

