# Local planner algorithm - actually selected Dynamic Window Approach method
base_local_planner: "dwa_local_planner/DWAPlannerROS"

# Global planner algorithm - available alternatives are:
#  navfn/NavfnROS, global_planner/GlobalPlanner, carrot_planner/CarrotPlanner
base_global_planner: "global_planner/GlobalPlanner"

controller_frequency: 8.0
planner_patience: 3.0
controller_patience: 4.0
conservative_reset_dist: 2.5
recovery_behavior_enabled: true
clearing_rotation_allowed: true
planner_frequency: 0.0
