base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'wheel_joint_BL'
  right_wheel : 'wheel_joint_BR'
  publish_rate: 100.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
  twist_covariance_diagonal: [0.0001, 0.0001, 0.001, 0.001, 0.001, 0.001]

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 2.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: wheels_base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           :  0.4 # m/s
      min_velocity           : -0.4 # m/snm
      has_acceleration_limits: true
      max_acceleration       :  0.6 # m/s^2
      min_acceleration       : -0.6 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 2.0  # rad/s^2

