# Mandatory parameters
speed_lim_v: 1.0
speed_lim_w: 2.0

accel_lim_v: 0.4
accel_lim_w: 0.5

# Optional parameters
frequency: 200.0
decel_factor: 0.5

# Robot velocity feedback type:
#  0 - none (default)
#  1 - odometry
#  2 - end robot commands
robot_feedback: 0
