# Mandatory parameters
speed_lim_v: 0.8
speed_lim_w: 5.4

accel_lim_v: 1.0
accel_lim_w: 2.0

# Optional parameters
frequency: 20.0
decel_factor: 1.5

# Robot velocity feedback type:
#  0 - none (default)
#  1 - odometry
#  2 - end robot commands
robot_feedback: 1
