# Mandatory parameters
speed_lim_v: 1.2
speed_lim_w: 2.0

accel_lim_v: 1.0
accel_lim_w: 1.8

# Optional parameters
frequency: 100.0
decel_factor: 0.8

# Robot velocity feedback type:
#  0 - none (default)
#  1 - odometry
#  2 - end robot commands
robot_feedback: 0
